/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "on-primary": "#005d63",
        "secondary": "#d674ff",
        "error": "#ff716c",
        "primary-fixed-dim": "#00deec",
        "surface": "#0d0d15",
        "secondary-dim": "#bb00fc",
        "on-primary-container": "#005359",
        "primary-fixed": "#00eefc",
        "tertiary-fixed-dim": "#beee00",
        "tertiary-dim": "#beee00",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#acaab5",
        "inverse-on-surface": "#55545e",
        "surface-variant": "#252531",
        "secondary-fixed": "#f1c1ff",
        "on-tertiary-container": "#4a5e00",
        "on-primary-fixed-variant": "#005e64",
        "surface-tint": "#8ff5ff",
        "on-secondary-container": "#fff5fc",
        "on-secondary": "#390050",
        "error-container": "#9f0519",
        "primary-container": "#00eefc",
        "inverse-primary": "#006a71",
        "outline-variant": "#484751",
        "surface-container-high": "#1f1f29",
        "error-dim": "#d7383b",
        "tertiary": "#f3ffca",
        "surface-container-low": "#13131c",
        "surface-bright": "#2b2b38",
        "inverse-surface": "#fcf8ff",
        "surface-container-highest": "#252531",
        "on-primary-fixed": "#003f43",
        "surface-dim": "#0d0d15",
        "on-error": "#490006",
        "on-tertiary-fixed-variant": "#526900",
        "on-secondary-fixed-variant": "#8400b3",
        "tertiary-container": "#cafd00",
        "on-tertiary-fixed": "#3a4a00",
        "on-surface": "#f2effb",
        "on-error-container": "#ffa8a3",
        "outline": "#76747f",
        "on-background": "#f2effb",
        "primary": "#8ff5ff",
        "surface-container": "#191923",
        "secondary-fixed-dim": "#eaaeff",
        "primary-dim": "#00deec",
        "secondary-container": "#9900cf",
        "on-tertiary": "#516700",
        "tertiary-fixed": "#cafd00",
        "on-secondary-fixed": "#580079",
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        neon: {
          crimson: "#FF0A54",
          cyan: "#00E5FF",
          violet: "#4D00FF",
          blue: "#8AB4F8",
        },
        cyber: {
          void: "#05050A",
          dark: "#0A1128",
          surface: "#121A33",
        },
      },
      fontFamily: {
        display: ['Outfit', 'system-ui', 'sans-serif'],
        cyber: ['Orbitron', 'system-ui', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'DM Sans', 'system-ui', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "neon-pulse": {
          "0%, 100%": { boxShadow: "0 0 5px #FF0A54, 0 0 10px rgba(255,10,84,0.3)" },
          "50%": { boxShadow: "0 0 15px #FF0A54, 0 0 30px rgba(255,10,84,0.4), 0 0 45px rgba(255,10,84,0.15)" },
        },
        "neon-pulse-light": {
          "0%, 100%": { boxShadow: "0 0 3px rgba(77,0,255,0.3), 0 0 8px rgba(77,0,255,0.15)" },
          "50%": { boxShadow: "0 0 8px rgba(77,0,255,0.4), 0 0 20px rgba(77,0,255,0.2)" },
        },
        "cyber-scan": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
        "border-glow": {
          "0%, 100%": { borderColor: "rgba(255,10,84,0.4)" },
          "50%": { borderColor: "rgba(255,10,84,0.8)" },
        },
        "border-glow-light": {
          "0%, 100%": { borderColor: "rgba(77,0,255,0.3)" },
          "50%": { borderColor: "rgba(77,0,255,0.6)" },
        },
        "glow-rotate": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease-out",
        "slide-up": "slide-up 0.6s ease-out",
        shimmer: "shimmer 2s linear infinite",
        float: "float 3s ease-in-out infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "neon-pulse": "neon-pulse 2s ease-in-out infinite",
        "neon-pulse-light": "neon-pulse-light 2s ease-in-out infinite",
        "cyber-scan": "cyber-scan 8s linear infinite",
        "border-glow": "border-glow 3s ease-in-out infinite",
        "border-glow-light": "border-glow-light 3s ease-in-out infinite",
        "glow-rotate": "glow-rotate 3s ease infinite",
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
